Table Cliente {
  cliente_id int [pk, increment]
  nome varchar
  cpf varchar [unique]
  email varchar [unique]
  telefone varchar
  endereco varchar
  data_nascimento date
  cnh_numero varchar
  cnh_validade date
  data_cadastro datetime
  status varchar
}

Table Funcionario {
  funcionario_id int [pk, increment]
  nome varchar
  email varchar [unique]
  senha_hash varchar
  perfil_acesso varchar
  data_cadastro datetime
  status varchar
}

Table Veiculo {
  veiculo_id int [pk, increment]
  placa varchar [unique]
  modelo varchar
  ano int
  cor varchar
  quilometragem int
  categoria varchar
  status varchar
  diaria_padrao decimal
  data_cadastro datetime
}

Table Tarifa {
  tarifa_id int [pk, increment]
  categoria varchar
  periodo varchar
  valor decimal
  alta_temporada boolean
  data_inicio date
  data_fim date
}

Table Adicional {
  adicional_id int [pk, increment]
  descricao varchar
  valor_diaria decimal
}

Table Reserva {
  reserva_id int [pk, increment]
  cliente_id int [ref: > Cliente.cliente_id]
  veiculo_id int [ref: > Veiculo.veiculo_id]
  data_retirada_prevista date
  hora_retirada_prevista time
  data_devolucao_prevista date
  hora_devolucao_prevista time
  valor_previsto decimal
  status varchar
  data_criacao datetime
}

Table Reserva_Adicional {
  reserva_id int [ref: > Reserva.reserva_id]
  adicional_id int [ref: > Adicional.adicional_id]
}

Table Locacao {
  locacao_id int [pk, increment]
  reserva_id int [ref: > Reserva.reserva_id, null]
  cliente_id int [ref: > Cliente.cliente_id]
  veiculo_id int [ref: > Veiculo.veiculo_id]
  data_retirada_real date
  hora_retirada_real time
  data_devolucao_real date
  hora_devolucao_real time
  valor_final decimal
  status varchar
}

Table Locacao_Adicional {
  locacao_id int [ref: > Locacao.locacao_id]
  adicional_id int [ref: > Adicional.adicional_id]
}

Table Historico_Avarias {
  avaria_id int [pk, increment]
  locacao_id int [ref: > Locacao.locacao_id]
  descricao text
  data_registro datetime
}
